import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import Layout from "./Component/Layout/Layout";



export const metadata: Metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <Layout>
       {children}
       <Toaster
          position="bottom-right"
          toastOptions={
            {
              duration: 1000,
              style: {
                background: '#000000',
                color: '#ffffff',
              },
            }
          }
        />
       </Layout>
      </body>
    </html>
  );
}
